// data.ts
export const pets = [
  {
    id: 1,
    name: "Rio",
    img: "https://images.unsplash.com/photo-1612831662375-295c1003d3db",
    breed: "Labrador Retriever",
    gender: "Male",
    age: "8 Weeks",
    city: "Mumbai",
    price: 45000,
  },
  {
    id: 2,
    name: "Bella",
    img: "https://images.unsplash.com/photo-1558788353-f76d92427f16",
    breed: "Golden Retriever",
    gender: "Female",
    age: "10 Weeks",
    city: "Delhi",
    price: 52000,
  },
  {
    id: 3,
    name: "Max",
    img: "https://images.unsplash.com/photo-1507149833265-60c372daea22",
    breed: "Beagle",
    gender: "Male",
    age: "9 Weeks",
    city: "Bengaluru",
    price: 38000,
  },
  {
    id: 4,
    name: "Lucy",
    img: "https://images.unsplash.com/photo-1593134257781-3cc0d8a25f90",
    breed: "Shih Tzu",
    gender: "Female",
    age: "7 Weeks",
    city: "Chennai",
    price: 40000,
  },
  {
    id: 5,
    name: "Rocky",
    img: "https://images.unsplash.com/photo-1543466835-00a7907e9de1",
    breed: "Siberian Husky",
    gender: "Male",
    age: "11 Weeks",
    city: "Hyderabad",
    price: 60000,
  },
  {
    id: 6,
    name: "Milo",
    img: "https://images.unsplash.com/photo-1619983081563-430f636027b4",
    breed: "German Shepherd",
    gender: "Male",
    age: "10 Weeks",
    city: "Pune",
    price: 55000,
  },
  {
    id: 7,
    name: "Luna",
    img: "https://images.unsplash.com/photo-1517849845537-4d257902454a",
    breed: "Poodle",
    gender: "Female",
    age: "9 Weeks",
    city: "Ahmedabad",
    price: 42000,
  },
  {
    id: 8,
    name: "Simba",
    img: "https://images.unsplash.com/photo-1616443104899-6c3b7b0de9ef",
    breed: "Rottweiler",
    gender: "Male",
    age: "8 Weeks",
    city: "Kolkata",
    price: 50000,
  },
  {
    id: 9,
    name: "Zoe",
    img: "https://images.unsplash.com/photo-1601758064221-0c3b3e5084d3",
    breed: "Pomeranian",
    gender: "Female",
    age: "7 Weeks",
    city: "Jaipur",
    price: 35000,
  },
  {
    id: 10,
    name: "Teddy",
    img: "https://images.unsplash.com/photo-1507149833265-60c372daea22",
    breed: "Chow Chow",
    gender: "Male",
    age: "12 Weeks",
    city: "Lucknow",
    price: 58000,
  },
  // ————————————————————————————————————————————————
  // Repeated and randomized below (90 more entries)
  ...Array.from({ length: 90 }, (_, i) => {
    const breeds = [
      "Shih Tzu",
      "Golden Retriever",
      "Labrador Retriever",
      "Siberian Husky",
      "German Shepherd",
      "Beagle",
      "Poodle",
      "Rottweiler",
      "Pomeranian",
      "Chow Chow",
    ];
    const cities = [
      "Mumbai",
      "Delhi",
      "Bengaluru",
      "Chennai",
      "Hyderabad",
      "Pune",
      "Ahmedabad",
      "Kolkata",
      "Jaipur",
      "Lucknow",
      "Surat",
      "Indore",
      "Bhopal",
      "Chandigarh",
      "Nagpur",
      "Goa",
      "Noida",
      "Gurgaon",
      "Patna",
      "Kochi",
    ];
    const names = [
      "Milo",
      "Luna",
      "Rocky",
      "Coco",
      "Leo",
      "Bella",
      "Max",
      "Charlie",
      "Daisy",
      "Simba",
      "Zoe",
      "Bruno",
      "Chiku",
      "Muffin",
      "Buddy",
      "Rex",
      "Snowy",
      "Shadow",
      "Teddy",
      "Chloe",
    ];
    const randomBreed = breeds[Math.floor(Math.random() * breeds.length)];
    const randomCity = cities[Math.floor(Math.random() * cities.length)];
    const randomName = names[Math.floor(Math.random() * names.length)];
    const gender = Math.random() > 0.5 ? "Male" : "Female";
    const age = `${Math.floor(Math.random() * 7) + 6} Weeks`;
    const price = Math.floor(Math.random() * 30000) + 35000;
    const imgUrls = [
      "https://images.unsplash.com/photo-1612831662375-295c1003d3db",
      "https://images.unsplash.com/photo-1558788353-f76d92427f16",
      "https://images.unsplash.com/photo-1543466835-00a7907e9de1",
      "https://images.unsplash.com/photo-1619983081563-430f636027b4",
      "https://images.unsplash.com/photo-1517849845537-4d257902454a",
      "https://images.unsplash.com/photo-1593134257781-3cc0d8a25f90",
      "https://images.unsplash.com/photo-1507149833265-60c372daea22",
      "https://images.unsplash.com/photo-1601758064221-0c3b3e5084d3",
      "https://images.unsplash.com/photo-1616443104899-6c3b7b0de9ef",
    ];
    const img = imgUrls[Math.floor(Math.random() * imgUrls.length)];
    return {
      id: i + 11,
      name: randomName,
      img,
      breed: randomBreed,
      gender,
      age,
      city: randomCity,
      price,
    };
  }),
];

export const popularBreeds = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "Pomeranian",
  "Beagle",
  "Husky",
  "Bulldog",
  "Pug",
];

export const breeds = [
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Pug",
  "Beagle",
  "Bulldog",
  "Rottweiler",
  "Poodle",
  "Siberian Husky",
  "Doberman",
];

export const statesWithCities: Record<string, string[]> = {
  Maharashtra: ["Mumbai", "Pune", "Nagpur"],
  Delhi: ["New Delhi", "Dwarka", "Rohini"],
  Karnataka: ["Bengaluru", "Mysuru", "Mangalore"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Noida"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara"],
};
